authapp/urls.py
from django.urls import path
from authapp.views import authentication, logout, profile, register

app_name = 'authapp'
urlpatterns = [
    path('auth/', authentication, name='authentication'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('register/', register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls),
               path("", include("mainapp.urls", namespace="main")),
               path("auth/", include("authapp.urls", namespace='authapp')),
               ]

mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import PostDetail, contacts, genre, main

app_name = "mainapp"

urlpatterns = [
    path("", main, name="main"),
    path("contacts/", contacts, name="contacts"),
    path("<int:pk>/", genre, name="genre"),
    path("performance/<int:pk>/", PostDetail.as_view(), name="post_detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    age = models.PositiveSmallIntegerField(verbose_name='Возраст', blank=True, null=True)
    avatar = models.ImageField(verbose_name='Аватар', blank=True, null=True, upload_to='users_avatar')

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

mainapp/models.py
from django.db import models


# from django.contrib import
class Genre(models.Model):
    title = models.CharField(max_length=30, verbose_name="Жанр")
    desc = models.TextField(verbose_name="Описание", blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Artist(models.Model):
    MALE = "ML"
    FEMALE = "FM"
    GENDER = [(MALE, "male"), (FEMALE, "female")]
    name = models.CharField(max_length=30, verbose_name="Имя артиста")
    middle_name = models.CharField(max_length=30, verbose_name="Отчество")
    surname = models.CharField(max_length=50, verbose_name="Фамилия артиста")
    age = models.SmallIntegerField(verbose_name="возраст")
    gender = models.CharField(verbose_name="Гендер", choices=GENDER, default=MALE, max_length=2)
    profession = models.CharField(verbose_name="Профессия", max_length=40)
    bio = models.TextField(blank=True, null=True, verbose_name="биография")
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True, verbose_name="Аватар")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Артист"
        verbose_name_plural = "Артисты"


class Repertoire(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название произведения", unique=True)
    genre = models.ManyToManyField(Genre, verbose_name="Жанр")
    year = models.SmallIntegerField(verbose_name="Год постановки")
    description = models.TextField(verbose_name="Описание")
    artist = models.ManyToManyField(Artist, verbose_name="Артист", related_name="repertoire")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Репертуар"
        verbose_name_plural = "Репертуар"


class Contact(models.Model):
    phone = models.IntegerField(verbose_name='Номер телефона', null=True, blank=True)
    email = models.EmailField(verbose_name='почта')

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return self.email



authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm
from authapp.models import User


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = 'form-control'

    class Meta:
        model = User
        fields = ("username", "password")


class UserEditForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = 'form-control'

    class Meta:
        model = User
        fields = ('avatar', 'first_name', 'last_name', 'age')


class UserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = 'form-control'

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'age', 'password1', 'password2', 'email')

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.contrib import auth
from django.conf import settings
from authapp.models import User
from authapp.forms import UserLoginForm, UserEditForm, UserRegisterForm


def authentication(request):
    title = 'Вход'
    login_form = UserLoginForm(data=request.POST or None)
    if request.method == 'POST' and login_form.is_valid:
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('mainapp:main'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('mainapp:main'))


def profile(request):
    title = 'Профиль'

    if request.method == 'POST':
        edit_form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('mainapp:main'))

    edit_form = UserEditForm(instance=request.user)
    content = {
        'title': title, 'edit_form': edit_form, 'media_url': settings.MEDIA_URL
    }
    return render(request, 'authapp/edit_profile.html', content)


def register(request):
    title = 'Регистрация'
    if request.method == 'POST':
        register_form = UserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        register_form = UserRegisterForm()
    content = {'title': title, 'register_form': register_form}
    return render(request, 'authapp/register.html', content)

mainapp/views.py
from datetime import datetime

from django.conf import settings
from django.shortcuts import render
from django.views.generic import DetailView
from mainapp.models import Artist, Contact, Genre, Repertoire


def main(request):
    artists = Artist.objects.all()
    links = Genre.objects.all()
    context = {'title': 'ГлАвНаЯ', 'time': datetime.now(), 'artists': artists, 'links': links,
               'media_url': settings.MEDIA_URL}
    return render(request, 'mainapp/index.html', context)


def contacts(request):
    contacts = Contact.objects.all()
    context = {'title': 'КоНтАкТы', 'time': datetime.now(), 'contacts': contacts}
    return render(request, 'mainapp/contacts.html', context)


def genre(request, pk=None):
    title = Genre.objects.get(pk=pk)
    links = Genre.objects.all()
    work = Repertoire.objects.filter(genre=pk)
    context = {'links': links, 'work': work, 'time': datetime.now(), 'title': title, 'media_url': settings.MEDIA_URL}
    return render(request, 'mainapp/works.html', context)


class PostDetail(DetailView):
    model = Repertoire
    template_name = 'mainapp/repertoire.html'

authapp/templates/authapp/edit_profile.html
{% extends 'authapp/include/inc_base.html' %}
{% load static %}
{% block content %}
{% if user.avatar %}
<img src="{{media_url}}{{user.avatar}}" class="avatar">
{% endif %}
<form class="form-horizontal" action="{% url 'authapp:profile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{edit_form.as_p}}
    <input type="submit" value="Сохранить">
</form>
{% endblock content %}

authapp/templates/authapp/include/inc_base.html
{% load static %}
{% block head %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock css %}
    {% block js %}

    {% endblock js %}
</head>
{% endblock head %}


<body>
<div class="container">
    <div class="content">
        {% block menu %}
        {% include 'mainapp/include/inc_menu.html' %}
        {% endblock menu %}
        {% block content %}
        {% endblock content %}
    </div>
    <div class="footer">
        {% block footer %}
        <a href="/">Footer</a>
        <p class="date">{{ time }}</p>
        {% endblock footer %}
    </div>
</div>
</body>

authapp/templates/authapp/login.html
{% extends 'authapp/include/inc_base.html' %}
{% load static %}
{% block content %}
<form class="form-horizontal" action="{% url 'authapp:authentication' %}" method="post">
    {% csrf_token %}
    {{login_form.as_p}}
    <input class="form-control" type="submit" value="Войти">
</form>
<li>
    <a href="{% url 'authapp:register' %}">Зарегистрироваться</a>
</li>

{% endblock content %}

authapp/templates/authapp/register.html
{% extends 'authapp/include/inc_base.html' %}
{% load static %}
{% block content %}
<form class="form-horizontal" action="{% url 'authapp:register' %}" method="post">
    {% csrf_token %}
    {{register_form.as_p}}
    <input type="submit" value="Зарегистрироваться">
</form>
{% endblock content %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/include/inc_base.html'%}
{% load static %}
{% block content %}

{% for contact in contacts %}
    {{contact.phone}}
    {{contact.email}}
{% endfor %}

{% endblock content %}

mainapp/templates/mainapp/include/inc_base.html
{% load static %}
{% block head %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    {% endblock css %}
    {% block js %}

    {% endblock js %}
</head>
{% endblock head %}


<body>
<div class="container">
    <div class="content">
        {% block menu %}
            {% include 'mainapp/include/inc_menu.html' %}
        {% endblock menu %}
        {% block content %}
        {% endblock content %}
    </div>
    <div class="footer">
        {% block footer %}
        <a href="/">Footer</a>
        <p class="date">{{ time }}</p>
        {% endblock footer %}
    </div>
</div>
</body>

mainapp/templates/mainapp/include/inc_menu.html
<div class="menu">
    <a href="{% url 'mainapp:main' %}" class="logo"><b>Арзамасский </b>театр<div>драммы</div></a>
    <a href="{% url 'mainapp:contacts' %}"
       class="{% if request.resolver_match.url_name == 'contacts' %}active{% endif %} one_menu">Контакты</a>
    {% for link in links %}
    <a href="{% url 'mainapp:genre' link.pk %}"
       class="{% if request.resolver_match.url_name == 'link' %}active{% endif %} one_menu">{{link.title}}</a>
    {% endfor %}
    {% if request.user.is_authenticated %}
    <a href="{% url 'authapp:profile' %}" class="one_menu">{{user.username|default:'user'}}</a>
    <a href="{% url 'authapp:logout' %}" class="one_menu">Выйти</a>
    {% else %}
    <a href="{% url 'authapp:register' %}" class="one_menu">Зарегистрироваться</a>
    <a href="{% url 'authapp:authentication' %}" class="one_menu">Войти</a>
    {% endif %}
</div>


mainapp/templates/mainapp/index.html
{% extends 'mainapp/include/inc_base.html' %}
{% load static %}
{% block content %}
<h1 class="titleclass">Драмматический театр</h1>
{% for artist in artists %}
<img src="{{media_url}}{{artist.avatar}}" class="avatar">
<p>{{ artist.name }}</p>
<p>{{ artist.middlename }}</p>
<p>{{ artist.surname }}</p>
<p>{{ artist.age }}</p>
<p>{{ artist.repertoire.title }}</p>
{% endfor %}
{% endblock content %}


mainapp/templates/mainapp/repertoire.html
{% extends 'mainapp/include/inc_base.html' %}
{% load static %}
{% block content %}
<div class="card">
    <li>{{repertoire.title}}</li>
    <li>{{repertoire.year}}</li>
    <br>
    <li>{% for actor in repertoire.artist.all %}
        {{ actor.name }}
        {{ actor.middlename }}
        {{ actor.surname }}
        <br>
        {% endfor %}
    </li>
    <br>
    <li>{{repertoire.description}}</li>
</div>
{% endblock %}

mainapp/templates/mainapp/works.html
{% extends 'mainapp/include/inc_base.html' %}
{% load static %}
{% block content %}
    {% for w in work %}
        <p class="proizved"><a href="{% url 'main:post_detail' w.pk %}">{{w.title}}</a></p>
    {% endfor %}
{% endblock %}